global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

alerting:
  alertmanagers:
  - static_configs:
    - targets:
     
rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: exporter
    scrape_interval: 10s
    static_configs:
    - targets: ['nginx-prometheus-exporter:9113']
  - job_name: pushgateway
    scrape_interval: 10s
    static_configs:
    - targets: ['prometheus-pushgateway:9091']
